# =============================================================================
# Program Name: HW_NN_Classifier_LastName_Firstname.py
# Purpose: This program was automatically generated by the Trainer program[cite: 81]. 
#          It reads validation data and classifies drivers using the fixed 
#          threshold discovered during training[cite: 97, 105].
# =============================================================================
import csv
import sys

def classify_data(input_filename):
    output_filename = 'HW_NN_LastName_FirstName_MyClassifications.csv'
    
    with open(input_filename, mode='r') as in_file, open(output_filename, mode='w', newline='') as out_file:
        csv_reader = csv.reader(in_file)
        csv_writer = csv.writer(out_file)
        
        header_row = next(csv_reader)
        # Add our guessed intent to the header
        header_row.append('Guessed_Intent')
        csv_writer.writerow(header_row)
        
        speed_index = header_row.index('Speed')
        
        for current_row in csv_reader:
            # Must quantize exactly the same way as the trainer! [cite: 199]
            speed_val = int(round(float(current_row[speed_index])))
            
            # Apply the fixed threshold [cite: 97]
            if speed_val >= 63:
                guessed_intent = 2 # aggressive [cite: 98]
            else:
                guessed_intent = 1 # non-aggressive [cite: 100]
                
            current_row.append(guessed_intent)
            csv_writer.writerow(current_row)
            
            # Print to standard output as required [cite: 103]
            print(guessed_intent)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Please provide the validation CSV filename as a parameter.")
    else:
        classify_data(sys.argv[1])
