# =============================================================================
# Program Name: HW_NN_Classifier_Le_Huy.py
# Purpose: This program was automatically generated by the Trainer program. 
#          It reads validation data and classifies drivers using the fixed 
#          threshold discovered during training.
# =============================================================================
import csv
import sys

def classify_data(input_filename):

    """
    Reads validation data and classifies driver intent using a fixed speed threshold.

    This function opens a provided CSV file containing driving records, extracts 
    the 'Speed' attribute, and quantizes it to the nearest integer. It then applies 
    a hardcoded threshold (discovered during the training phase) to predict if the 
    driver is non-aggressive (1) or aggressive (2). The predictions are printed to 
    the console and saved as a new column in an output CSV file.

    Args:
        input_filename (str): The relative or absolute file path to the 
            validation CSV file. The CSV must contain a header row with a 
            'Speed' column.

    Returns:
        None: The function does not return a value. Instead, it writes the 
            results to 'HW_NN_Le_Huy_MyClassifications.csv' and prints 
            the classifications to standard output.

    Raises:
        FileNotFoundError: If the provided `input_filename` does not exist.
        ValueError: If the 'Speed' column contains data that cannot be 
            converted to a float.
    """

    output_filename = 'HW_03_Le1_MyClassifications.csv'
    
    with open(input_filename, mode='r') as in_file, open(output_filename, mode='w', newline='') as out_file:
        csv_reader = csv.reader(in_file)
        csv_writer = csv.writer(out_file)
        
        header_row = next(csv_reader)
        # Add our guessed intent to the header
        header_row.append('Guessed_Intent')
        csv_writer.writerow(header_row)
        
        speed_index = header_row.index('Speed')
        
        for current_row in csv_reader:
            # Must quantize exactly the same way as the trainer!
            speed_val = int(float(current_row[speed_index])+0.5)
            
            # Apply the fixed threshold
            if speed_val >= 63:
                guessed_intent = 2 # aggressive
            else:
                guessed_intent = 1 # non-aggressive
                
            current_row.append(guessed_intent)
            csv_writer.writerow(current_row)
            
            # Print to standard output as required
            print(guessed_intent)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Please provide the validation CSV filename as a parameter.")
    else:
        classify_data(sys.argv[1])
