# =============================================================================
# Program Name: HW_05_Classifier_Le_Huy.py
# Author: Huy Le (hl9082)
# Purpose: Auto-generated Decision Tree classifier for Abominable SnowFolk.
# =============================================================================
import csv # csv is used to read from and write to CSV files, which is how our validation data will be provided
import sys # sys is used to handle command-line arguments and exit gracefully if there are issues with the file points
 
def classify_data(filename):
    """
    Reads validation data and classifies it using the hardcoded Decision Tree logic.

    This function opens the specified CSV file, pre-quantizes the input features
    (rounding to the nearest 2.0) exactly as they were pre-processed during training, 
    and applies a series of auto-generated if/else statements to predict the 
    specimen's class. The resulting classification (-1 for Assam, +1 for Bhuttan) 
    is printed directly to standard output for each row.

    Args:
        filename (str): The relative or absolute path to the validation CSV file.

    Returns:
        None: Output is printed to stdout.

    Raises:
        SystemExit: If the provided filename does not exist.
    """
    print(f"Reading and classifying data from: {filename}\n")
    
    try:
        with open(filename, mode='r') as file:
        # csv.DictReader reads the file line-by-line and maps each value to its column header name, 
        # allowing us to access data via row['Age']
            csv_reader = csv.DictReader(file)
            
            for row in csv_reader:
                # 1. Extract raw floats first to prevent string parsing errors
                raw_Age = float(row['Age'])
                raw_Ht = float(row['Ht'])
                raw_TailLn = float(row['TailLn'])
                raw_HairLn = float(row['HairLn'])
                raw_HairClr = int(row['HairClr'])
                raw_BangLn = float(row['BangLn'])
                raw_Reach = float(row['Reach'])
                raw_EarLobes = int(row['EarLobes'])
                
                # 2. Generate the derived features
                raw_Shagginess = raw_HairLn - raw_BangLn
                raw_ApeFactor = raw_Reach - raw_Ht

                # 3. Quantize to nearest 1 (rounding)
                Age = round(raw_Age)
                Ht = round(raw_Ht)
                TailLn = round(raw_TailLn)
                HairLn = round(raw_HairLn)
                HairClr = int(round(raw_HairClr))
                BangLn = round(raw_BangLn)
                Reach = round(raw_Reach)
                EarLobes = int(round(raw_EarLobes))
                Shagginess = round(raw_Shagginess)
                ApeFactor = round(raw_ApeFactor)

                # =====================================================================
                # --- DECISION TREE LOGIC ---
                # This block was dynamically generated by the Trainer using 
                # metaprogramming. The Trainer fit a scikit-learn tree using Average Entropy, 
                # max_depth=5, and min_samples=23. 
                # 
                # Scikit-learn does not natively support 
                # pre-pruning at an arbitrary 85% purity threshold. Therefore, this tree 
                # split based on the strict Entropy criterion down to 100% purity, unless 
                # stopped early by the depth (5) or sample size (23) constraints!
                # =====================================================================
                if ApeFactor <= 5.0:
                    if BangLn <= 7.0:
                        if HairLn <= 11.0:
                            if Age <= 43.0:
                                if Shagginess <= 3.0:
                                    predicted_class = -1 # Assam
                                else:
                                    predicted_class = -1 # Assam
                            else:
                                if Reach <= 133.0:
                                    predicted_class = -1 # Assam
                                else:
                                    predicted_class = -1 # Assam
                        else:
                            predicted_class = -1 # Assam
                    else:
                        if Age <= 47.0:
                            if HairLn <= 9.0:
                                predicted_class = -1 # Assam
                            else:
                                predicted_class = 1 # Bhuttan
                        else:
                            predicted_class = -1 # Assam
                else:
                    if BangLn <= 5.0:
                        if HairLn <= 11.0:
                            if TailLn <= 9.0:
                                if Age <= 49.0:
                                    predicted_class = -1 # Assam
                                else:
                                    predicted_class = -1 # Assam
                            else:
                                if Ht <= 137.0:
                                    predicted_class = -1 # Assam
                                else:
                                    predicted_class = -1 # Assam
                        else:
                            predicted_class = -1 # Assam
                    else:
                        if BangLn <= 7.0:
                            if HairLn <= 9.0:
                                if Age <= 53.0:
                                    predicted_class = 1 # Bhuttan
                                else:
                                    predicted_class = -1 # Assam
                            else:
                                if HairLn <= 11.0:
                                    predicted_class = 1 # Bhuttan
                                else:
                                    predicted_class = 1 # Bhuttan
                        else:
                            if HairLn <= 11.0:
                                if Ht <= 135.0:
                                    predicted_class = 1 # Bhuttan
                                else:
                                    predicted_class = 1 # Bhuttan
                            else:
                                if Reach <= 137.0:
                                    predicted_class = 1 # Bhuttan
                                else:
                                    predicted_class = 1 # Bhuttan

                # Print out the class value for each line of the test data file
                print(predicted_class)
                
    except FileNotFoundError: # print the error and exit if we can't find the validation data
        print(f"ERROR: File '{filename}' not found.")
        sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python HW_05_Classifier_Le_Huy.py <ValidationData.csv>")
    else:
        classify_data(sys.argv[1])
